name: Publish to CurseForge

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish to CurseForge
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          version: ${{ inputs.version }}
          version-type: release
          name: "[${{ inputs.version }}] CRNet"
          changelog-file: CHANGELOG.md
          loaders: neoforge
          game-versions: 1.21.1
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          java: 21

          curseforge-id: 1509069
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

      - name: Publish to GitHub Packages
        run: ./gradlew publish -Pmod_version=${{ inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
