name: Publish

on:
  workflow_dispatch:
    inputs:
      publish_maven:
        description: 'Push to Maven repo'
        type: boolean
        default: true
      publish_curseforge:
        description: 'Publish to CurseForge'
        type: boolean
        default: true

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Make Gradle wrapper executable
        run: chmod +x gradlew

      - name: Get version
        id: version
        run: echo "value=$(grep '^mod_version=' gradle.properties | cut -d'=' -f2)" >> $GITHUB_OUTPUT

      - name: Build with Gradle
        run: ./gradlew build

      - name: Publish artifacts
        if: ${{ inputs.publish_maven }}
        run: ./gradlew publish

      - name: Push to Maven repo
        if: ${{ inputs.publish_maven }}
        run: |
          git clone https://x-access-token:${{ secrets.MAVEN_REPO_TOKEN }}@github.com/matejhozlar/maven.git maven-repo
          cp -r build/maven-publish/. maven-repo/
          cd maven-repo
          git config user.email "ci@createrington.com"
          git config user.name "CI"
          git add .
          git diff --cached --quiet || git commit -m "publish crnet ${{ steps.version.outputs.value }}"
          git push

      - name: Publish to CurseForge
        if: ${{ inputs.publish_curseforge }}
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          version: ${{ steps.version.outputs.value }}
          version-type: beta
          name: "[${{ steps.version.outputs.value }}] CRNet"
          changelog-file: CHANGELOG.md
          loaders: neoforge
          game-versions: 1.21.1
          files: build/libs/!(*-@(dev|sources|javadoc)).jar
          java: 21

          curseforge-id: 1509069
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}

          github-token: ${{ secrets.GITHUB_TOKEN }}
